### ISSUE TITLE
What is the apps folder for

### ISSUE THREAD

**Issue by CapedBojji** [bddvlpr/resonance#2]
Hello there, Great dot files. I was wondering what the apps folder was for. I like your architecture.

**Comment by bddvlpr** [comment]
I used to use this to define flake's `apps.${system}.<run-name>` apps (flake-parts example below). Aka, just a bunch of programs I could start with `nix run .#<run-name>`. This isn't being used anymore and I most likely will never use it again as I'd rather just set up a devenv with said program.

```nix
{
  perSystem = {pkgs, ...}: {
    # run this with `nix run .#helloworld`
    apps.helloworld = {
      type = "app";
      program = "${pkgs.hello}/bin/hello";
    };
  };
}
```
